### ISSUE TITLE
FileExistsError

### ISSUE THREAD

**Issue by simon376** [navarasu/opencv-log#36] opened 2020-06-09 08:01 UTC
**Describe the bug**
when one tries to create logs shortly after each other, the renaming does not work

**To Reproduce**
1. log to HTML file
2. (change some code) 
3. log again to HTML file
4. log.image(log.Level.INFO, img) 

FileExistsError: file could not be created, because it already exists: 'log\\cvlog.html' -> 'log\\cvlog_20-06-08.163919.html'

**Expected behavior**
rename file so there's no error or overwrite it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.8 32bit
 - opencv-python 4.2.0.34
 - opencv-log 1.2.2

**Comment by navarasu** [comment] 2020-06-09 09:12
Thanks for logging the issue. This is windows specific issue in getting the file modified time. This issue will be fixed in 1.3.0 release.

**Comment by navarasu** [comment] 2020-06-17 14:41
@simon376  What do you mean 'log to HTML file' in steps 1 & 3? is 1 & 3  not the same as 4?

**Comment by navarasu** [comment] 2020-06-17 14:51
I created a test case to reproduce this issue in windows. But it is not able to reproduce manually in real-time. Thinking how to you reproduce these steps. 

```python
def test_log_rotation():
    remove_dirs('log/')
    html_logger = hl.HtmlLogger()
    html_logger.log_image('error', 'image', "dummy string", None)
    assert os.path.exists('check/cvlog.html') is True
    assert len(os.listdir('log/')) == 1
    html_logger = hl.HtmlLogger()
    html_logger.log_image('error', 'image', "dummy string", None)
    assert os.path.exists('check/cvlog.html') is True
    assert len(os.listdir('log/')) == 2
    html_logger = hl.HtmlLogger()
    html_logger.log_image('error', 'image', "dummy string", None)
    assert os.path.exists('check/cvlog.html') is True
    assert len(os.listdir('log/')) == 3
```

**Comment by simon376** [comment] 2020-06-17 16:02
when I run my script, logging to the HTML file, multiple times within some time, your library tries to rename the file from cvlog to cvlog_date.time.html.

it seems to me the _time_stamp_ variable gets cached or not changed correctly (I have no idea about OS file IO functions), which leads to it reusing a timestamp it used to rename before, so it fails renaming the file because it already exists.

**Comment by simon376** [comment] 2020-06-17 16:07
now I got it.

it seems like the creation time of the HTML file is not set properly.
if there is no cvlog.html file, the file creation timestamp is still the one used "last time" (which leads to the duplicates), while the last-changed timestamp is the correct one.

**Comment by navarasu** [comment] 2020-06-17 16:37
Are you removing  cvlog.html? Is it possible to share the script which reproduces these issues?

**Comment by navarasu** [comment] 2020-06-17 16:42
For every new python run, it backup the old HTML file as part of log rotation. It takes the file created time for renaming the old file.

**Comment by marisnb** [comment] 2020-06-17 18:25
Given the file exists error in windows
https://github.com/navarasu/opencv-log/pull/42

**Closed** 2020-06-17 18:27 UTC
Labels: bug

**Comment by navarasu** [comment] 2020-06-17 18:52
@simon376 Spun the new version release with this fix and lot more features.
